// Generated by scripts/sync-model-pricing.mjs. Do not edit by hand.
export const MODEL_PRICING = {
  "schemaVersion": 1,
  "source": "vercel-ai-gateway",
  "sourceUrl": "https://ai-gateway.vercel.sh/v1/models",
  "fetchedAt": "2026-08-31T10:51:42.634Z",
  "currency": "USD",
  "unit": "per_token",
  "models": {
    "openai/gpt-5.4-mini": {
      "input": 7.5e-7,
      "output": 0.0000045,
      "contextWindow": 400000,
      "maxTokens": 128000
    },
    "openai/gpt-5.4-nano": {
      "input": 2e-7,
      "output": 0.00000125,
      "contextWindow": 400000,
      "maxTokens": 128000
    },
    "openai/gpt-5.4": {
      "input": 0.0000025,
      "output": 0.000015,
      "contextWindow": 1050000,
      "maxTokens": 128000
    },
    "openai/gpt-5.5": {
      "input": 0.000005,
      "output": 0.00003,
      "contextWindow": 1000000,
      "maxTokens": 128000
    },
    "deepseek/deepseek-v4-flash": {
      "input": 1.3e-7,
      "output": 2.6e-7,
      "contextWindow": 1000000,
      "maxTokens": 384000
    },
    "deepseek/deepseek-v4-pro": {
      "input": 6.6e-7,
      "output": 0.00000198,
      "contextWindow": 1000000,
      "maxTokens": 384000
    },
    "moonshotai/kimi-k2.6": {
      "input": 9.5e-7,
      "output": 0.000004,
      "contextWindow": 262000,
      "maxTokens": 262000
    },
    "moonshotai/kimi-k2.5": {
      "input": 6e-7,
      "output": 0.000003,
      "contextWindow": 262114,
      "maxTokens": 262114
    },
    "zai/glm-4.7": {
      "input": 6e-7,
      "output": 0.0000022,
      "contextWindow": 200000,
      "maxTokens": 120000
    },
    "zai/glm-5": {
      "input": 0.000001,
      "output": 0.0000032,
      "contextWindow": 202800,
      "maxTokens": 131100
    },
    "zai/glm-5.1": {
      "input": 0.0000014,
      "output": 0.0000044,
      "contextWindow": 202800,
      "maxTokens": 64000
    },
    "xiaomi/mimo-v2.5": {
      "input": 1.4e-7,
      "output": 2.8e-7,
      "contextWindow": 1050000,
      "maxTokens": 131100
    },
    "xiaomi/mimo-v2.5-pro": {
      "input": 4.35e-7,
      "output": 8.7e-7,
      "contextWindow": 1050000,
      "maxTokens": 131000
    }
  }
} as const;
