export const MARKLINGO_CONFIGURATION_KEYS = [
  'openrouter.provider',
  'openrouter.baseUrl',
  'openrouter.modelId',
  'providers.openrouter.modelId',
  'providers.openai.modelId',
  'providers.deepseek.modelId',
  'providers.moonshot.modelId',
  'providers.glm.modelId',
  'providers.xiaomiMimo.modelId',
  'providers.openaiCompatible.baseUrl',
  'providers.openaiCompatible.modelId',
  'translation.targetLanguage',
  'translation.targetLanguageCustom',
  'translation.requestMode',
  'translation.maxBlocksPerRequest',
  'translation.maxContextUsageRatio',
  'translation.translationModelMaxBlocksPerRequest',
  'translation.translationModelConcurrency',
  'translation.translationModelMaxOutputTokens',
  'translation.systemPrompt',
  'translation.customPrompt',
] as const;
